$engine_version: 2
$minFxServerVersion: 7290

name: Double Sync Framework
version: 1.0.0
author: Double Sync Team
description: A comprehensive RedM framework with multi-character, modern HUD, and advanced features.

variables:
  dbHost: localhost
  dbUsername: root
  dbPassword: ""
  dbName: doublesync
  svLicense: changeme
  svMaxClients: 32

tasks:
  # Download framework from GitHub
  - action: download_github
    src: https://github.com/FarrofaDeBacon/DSCore
    ref: main
    dest: ./resources/[ds]/ds-core

  # Download oxmysql dependency
  - action: download_github
    src: https://github.com/overextended/oxmysql
    ref: master
    dest: ./resources/[standalone]/oxmysql
    
  # Remove .git folders
  - action: remove_path
    path: ./resources/[ds]/ds-core/.git
    
  - action: remove_path
    path: ./resources/[standalone]/oxmysql/.git

  # Create server.cfg
  - action: write_file
    path: ./server.cfg
    file: |
      # =====================================
      # Double Sync Framework - Server Config
      # =====================================
      
      # Server Information
      sv_hostname "Double Sync RP"
      sv_maxclients {{svMaxClients}}
      sets sv_projectName "Double Sync RP"
      sets sv_projectDesc "A RedM Roleplay Server powered by Double Sync Framework"
      
      # License Key
      sv_licenseKey "{{svLicense}}"
      
      # Database Connection
      set mysql_connection_string "mysql://{{dbUsername}}:{{dbPassword}}@{{dbHost}}/{{dbName}}?charset=utf8mb4"
      
      # Locale Settings
      setr ox:locale "en"
      
      # =====================================
      # Resources
      # =====================================
      
      # Dependencies
      ensure oxmysql
      
      # Double Sync Core
      ensure ds-core
      
      # Add your additional resources below
      # ensure ds-inventory
      # ensure ds-housing
      # ensure ds-jobs

  # Run database queries
  - action: query_database
    query: |
      CREATE DATABASE IF NOT EXISTS `{{dbName}}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

  - action: connect_database
    database: "{{dbName}}"

  - action: query_database
    query: |
      CREATE TABLE IF NOT EXISTS `ds_players` (
          `id` INT AUTO_INCREMENT PRIMARY KEY,
          `citizenid` VARCHAR(50) NOT NULL UNIQUE,
          `license` VARCHAR(100) NOT NULL,
          `name` VARCHAR(100),
          `charinfo` JSON DEFAULT '{}',
          `money` JSON DEFAULT '{"cash":100,"bank":500,"gold":0}',
          `job` JSON DEFAULT '{"name":"unemployed","label":"Unemployed","grade":0}',
          `gang` JSON DEFAULT '{"name":"none","label":"None","grade":0}',
          `position` JSON DEFAULT NULL,
          `metadata` JSON DEFAULT '{"hunger":100,"thirst":100,"stamina":100,"isdead":false}',
          `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          INDEX `idx_license` (`license`),
          INDEX `idx_citizenid` (`citizenid`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

  - action: query_database
    query: |
      CREATE TABLE IF NOT EXISTS `ds_logs` (
          `id` INT AUTO_INCREMENT PRIMARY KEY,
          `type` VARCHAR(50) NOT NULL,
          `source` INT,
          `citizenid` VARCHAR(50),
          `message` TEXT,
          `data` JSON,
          `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          INDEX `idx_type` (`type`),
          INDEX `idx_citizenid` (`citizenid`),
          INDEX `idx_created_at` (`created_at`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

  - action: query_database
    query: |
      CREATE TABLE IF NOT EXISTS `ds_bans` (
          `id` INT AUTO_INCREMENT PRIMARY KEY,
          `license` VARCHAR(100) NOT NULL,
          `discord` VARCHAR(50),
          `reason` TEXT,
          `banned_by` VARCHAR(100),
          `expire_at` TIMESTAMP NULL,
          `permanent` BOOLEAN DEFAULT FALSE,
          `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          INDEX `idx_license` (`license`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

  - action: query_database
    query: |
      CREATE TABLE IF NOT EXISTS `ds_inventory` (
          `id` INT AUTO_INCREMENT PRIMARY KEY,
          `citizenid` VARCHAR(50) NOT NULL,
          `items` JSON DEFAULT '[]',
          `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          INDEX `idx_citizenid` (`citizenid`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

  # Done message
  - action: waste_time
    seconds: 2

  - action: notify
    message: |
      Double Sync Framework installed successfully!
      
      Next Steps:
      1. Configure your server.cfg with the correct license key
      2. Start your server
      3. Connect and use /charselect to create a character
      
      Documentation: https://github.com/DoubleSync/ds-core
      
      Enjoy your new RedM server!
