$engine_version: 2
$minFxServerVersion: 7290

name: Double Sync Framework
version: 1.0.0
author: Double Sync Team
description: Complete RedM framework

variables:
    dbHost: localhost
    dbUsername: root
    dbPassword: ""
    dbName: doublesync
    svLicense: changeme
    svMaxClients: 32

tasks:
    - action: download_github
      src: https://github.com/FarrofaDeBacon/DSCore
      ref: main
      dest: ./resources/[ds]/ds-core

    - action: download_github
      src: https://github.com/overextended/oxmysql
      ref: master
      dest: ./resources/[standalone]/oxmysql

    - action: remove_path
      path: ./resources/[ds]/ds-core/.git

    - action: remove_path
      path: ./resources/[standalone]/oxmysql/.git

    - action: write_file
      path: server.cfg
      file: |
          sv_hostname "Double Sync RP"
          sv_maxclients {{svMaxClients}}
          sv_licenseKey "{{svLicense}}"
          set mysql_connection_string "mysql://{{dbUsername}}:{{dbPassword}}@{{dbHost}}/{{dbName}}?charset=utf8mb4"
          ensure oxmysql
          ensure ds-core

    - action: query_database
      query: CREATE DATABASE IF NOT EXISTS {{dbName}}

    - action: connect_database
      database: "{{dbName}}"

    - action: query_database
      query: CREATE TABLE IF NOT EXISTS ds_players (id INT AUTO_INCREMENT PRIMARY KEY, citizenid VARCHAR(50) NOT NULL, license VARCHAR(100) NOT NULL, name VARCHAR(100), charinfo JSON, money JSON, job JSON, position JSON, metadata JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)

    - action: query_database
      query: CREATE TABLE IF NOT EXISTS ds_inventory (id INT AUTO_INCREMENT PRIMARY KEY, citizenid VARCHAR(50) NOT NULL, items JSON, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)

    - action: waste_time
      seconds: 1

    - action: notify
      message: Double Sync Framework instalado com sucesso!
